'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BORepetitive.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBinFrom.
        '''</summary>
        Friend ReadOnly Property Param_iBinFrom() As String
            Get
                Return ResourceManager.GetString("Param_iBinFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBinFromQtyOnHand.
        '''</summary>
        Friend ReadOnly Property Param_iBinFromQtyOnHand() As String
            Get
                Return ResourceManager.GetString("Param_iBinFromQtyOnHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBinFromTrxQty.
        '''</summary>
        Friend ReadOnly Property Param_iBinFromTrxQty() As String
            Get
                Return ResourceManager.GetString("Param_iBinFromTrxQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBinTo.
        '''</summary>
        Friend ReadOnly Property Param_iBinTo() As String
            Get
                Return ResourceManager.GetString("Param_iBinTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBinToQtyOnHand.
        '''</summary>
        Friend ReadOnly Property Param_iBinToQtyOnHand() As String
            Get
                Return ResourceManager.GetString("Param_iBinToQtyOnHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBinToTrxQty.
        '''</summary>
        Friend ReadOnly Property Param_iBinToTrxQty() As String
            Get
                Return ResourceManager.GetString("Param_iBinToTrxQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCreateDate.
        '''</summary>
        Friend ReadOnly Property Param_iCreateDate() As String
            Get
                Return ResourceManager.GetString("Param_iCreateDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemCount.
        '''</summary>
        Friend ReadOnly Property Param_iItemCount() As String
            Get
                Return ResourceManager.GetString("Param_iItemCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iItemNo.
        '''</summary>
        Friend ReadOnly Property Param_iItemNo() As String
            Get
                Return ResourceManager.GetString("Param_iItemNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLoc.
        '''</summary>
        Friend ReadOnly Property Param_iLoc() As String
            Get
                Return ResourceManager.GetString("Param_iLoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLocFrom.
        '''</summary>
        Friend ReadOnly Property Param_iLocFrom() As String
            Get
                Return ResourceManager.GetString("Param_iLocFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLocFromQtyOnHand.
        '''</summary>
        Friend ReadOnly Property Param_iLocFromQtyOnHand() As String
            Get
                Return ResourceManager.GetString("Param_iLocFromQtyOnHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLocTo.
        '''</summary>
        Friend ReadOnly Property Param_iLocTo() As String
            Get
                Return ResourceManager.GetString("Param_iLocTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLocToQtyOnHand.
        '''</summary>
        Friend ReadOnly Property Param_iLocToQtyOnHand() As String
            Get
                Return ResourceManager.GetString("Param_iLocToQtyOnHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iord_no.
        '''</summary>
        Friend ReadOnly Property Param_iord_no() As String
            Get
                Return ResourceManager.GetString("Param_iord_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iOrderNo.
        '''</summary>
        Friend ReadOnly Property Param_iOrderNo() As String
            Get
                Return ResourceManager.GetString("Param_iOrderNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iQtyToMove.
        '''</summary>
        Friend ReadOnly Property Param_iQtyToMove() As String
            Get
                Return ResourceManager.GetString("Param_iQtyToMove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSessionID.
        '''</summary>
        Friend ReadOnly Property Param_iSessionID() As String
            Get
                Return ResourceManager.GetString("Param_iSessionID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to itran_type.
        '''</summary>
        Friend ReadOnly Property Param_iTran_type() As String
            Get
                Return ResourceManager.GetString("Param_iTran_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTransactionID.
        '''</summary>
        Friend ReadOnly Property Param_iTransactionID() As String
            Get
                Return ResourceManager.GetString("Param_iTransactionID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTranType.
        '''</summary>
        Friend ReadOnly Property Param_iTranType() As String
            Get
                Return ResourceManager.GetString("Param_iTranType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetCurrentBins.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetCurrentBins() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetCurrentBins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetItemLocation_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetItemLocation_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetItemLocation_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMGetQtyOnHand_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMGetQtyOnHand_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMGetQtyOnHand_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMInvBin_WRK.
        '''</summary>
        Friend ReadOnly Property SP_spIMInvBin_WRK() As String
            Get
                Return ResourceManager.GetString("SP_spIMInvBin_WRK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMInventoryTransHistory.
        '''</summary>
        Friend ReadOnly Property SP_spIMInventoryTransHistory() As String
            Get
                Return ResourceManager.GetString("SP_spIMInventoryTransHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spIMSaveRepetitiveLog_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spIMSaveRepetitiveLog_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spIMSaveRepetitiveLog_MAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
